/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MyBankApp;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Anton Roycar Nababan
 */
public class AdminUserMenu extends javax.swing.JFrame {

    /**
     * Creates new form AdminUserMenu
     */
    
    ConnectDB conDB = new ConnectDB();
    DefaultTableModel models;
    int curId = 0;
    public AdminUserMenu(int k) {
        conDB.connect();
        initComponents();
        setLocationRelativeTo(null);
        curId = k;
        nameUserLbl.setText(conDB.getUsername(k));
        idUserLbl.setText("" + k);
        changeBlock(k);
        models = (DefaultTableModel) jTable1.getModel();
        showAllData(k);
    }

    private void changeBlock(int k){
        if(conDB.getBlockInfo(k)){
            blockInfoLbl.setText("BLOCKED");
        } else{
            blockInfoLbl.setText("NOT BLOCKED");
        }
    }
    
    public void showAllData(int itu){
        ArrayList<BalanceData> bd = new ArrayList<BalanceData>();
        bd = conDB.getUserBalance(itu);
        for(int i = 0; i < bd.size(); i++){
            models.insertRow(models.getRowCount(), new Object[]{bd.get(i).getId(),bd.get(i).getDate(),bd.get(i).getPrevBalance(), bd.get(i).getAfterBalance(), bd.get(i).getTransaction()});
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        idTiitleLbl = new javax.swing.JLabel();
        idUserLbl = new javax.swing.JLabel();
        nameTittleLbl = new javax.swing.JLabel();
        nameUserLbl = new javax.swing.JLabel();
        blockStatusLbl = new javax.swing.JLabel();
        blockInfoLbl = new javax.swing.JLabel();
        delLastTransBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        balanceToChangeTF = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        balanceChangeDescTF = new javax.swing.JTextField();
        commitChangeBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        blockBtn = new javax.swing.JButton();
        unBlockBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Transaksi", "Tanggal", "Saldo Sebelum", "Saldo Setelah", "Keterangan"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        idTiitleLbl.setText("ID : ");

        idUserLbl.setText("ID USER");

        nameTittleLbl.setText("NAMA :");

        nameUserLbl.setText("NAMA PENGGUNA");

        blockStatusLbl.setText("Status Block : ");

        blockInfoLbl.setText("BLOCK");

        delLastTransBtn.setText("Hapus Transaksi Terakhir");
        delLastTransBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delLastTransBtnActionPerformed(evt);
            }
        });

        jLabel1.setText("Modifikasi Saldo");

        jLabel2.setText("Jumlah Saldo Diubah     : ");

        jLabel3.setText("Keterangan Perubahan : ");

        commitChangeBtn.setText("Lakukan Perubahan");
        commitChangeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                commitChangeBtnActionPerformed(evt);
            }
        });

        jLabel4.setText("NB: Tambahkan tanda - di jumlah saldo diubah jika ingin mengurangi saldo");

        backBtn.setText("Kembali");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        blockBtn.setText("Block User");
        blockBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blockBtnActionPerformed(evt);
            }
        });

        unBlockBtn.setText("Unblock User");
        unBlockBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unBlockBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(idTiitleLbl)
                        .addGap(18, 18, 18)
                        .addComponent(idUserLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(nameTittleLbl)
                        .addGap(18, 18, 18)
                        .addComponent(nameUserLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(blockStatusLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(blockInfoLbl))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(delLastTransBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(blockBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(unBlockBtn))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(commitChangeBtn)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(balanceChangeDescTF))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(balanceToChangeTF, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(backBtn)
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idTiitleLbl)
                    .addComponent(idUserLbl)
                    .addComponent(nameTittleLbl)
                    .addComponent(nameUserLbl)
                    .addComponent(blockStatusLbl)
                    .addComponent(blockInfoLbl))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(delLastTransBtn)
                    .addComponent(blockBtn)
                    .addComponent(unBlockBtn))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(balanceToChangeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(balanceChangeDescTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(commitChangeBtn)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(backBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void delLastTransBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delLastTransBtnActionPerformed
        // TODO add your handling code here:    
        conDB.delLastTrans(curId);
        models.setRowCount(0);
        showAllData(curId);
    }//GEN-LAST:event_delLastTransBtnActionPerformed

    private void commitChangeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_commitChangeBtnActionPerformed
        // TODO add your handling code here:
        int amon = Integer.parseInt(balanceToChangeTF.getText());
        String descc = balanceChangeDescTF.getText();
        conDB.adminPushChange(curId, amon, descc);
        models.setRowCount(0);
        showAllData(curId);
    }//GEN-LAST:event_commitChangeBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        new AdminMenu().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_backBtnActionPerformed

    private void blockBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blockBtnActionPerformed
        // TODO add your handling code here:
        conDB.adminblockUSer(curId);
        changeBlock(curId);
    }//GEN-LAST:event_blockBtnActionPerformed

    private void unBlockBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unBlockBtnActionPerformed
        // TODO add your handling code here:
        conDB.adminUnblockUSer(curId);
        changeBlock(curId);
    }//GEN-LAST:event_unBlockBtnActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JTextField balanceChangeDescTF;
    private javax.swing.JTextField balanceToChangeTF;
    private javax.swing.JButton blockBtn;
    private javax.swing.JLabel blockInfoLbl;
    private javax.swing.JLabel blockStatusLbl;
    private javax.swing.JButton commitChangeBtn;
    private javax.swing.JButton delLastTransBtn;
    private javax.swing.JLabel idTiitleLbl;
    private javax.swing.JLabel idUserLbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel nameTittleLbl;
    private javax.swing.JLabel nameUserLbl;
    private javax.swing.JButton unBlockBtn;
    // End of variables declaration//GEN-END:variables
}
