/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MyBankApp;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Anton Roycar Nababan
 */
public class BalancePage extends javax.swing.JFrame {

    /**
     * Creates new form BalancePage
     */
    ConnectDB conDB = new ConnectDB();
    DefaultTableModel models;
    public BalancePage(String a, int it) {
        
        conDB.connect();
        initComponents();
        setLocationRelativeTo(null);
        usernameLbl.setText(a);
        models = (DefaultTableModel) balanceDataTbl.getModel();
        showAllData(it);
        currentId = it;
        balSUMAmountLbl.setText("" + conDB.getLastBalance(it));
    }

    public void reloadData(){
        models.setRowCount(0);
        showAllData(currentId);
    }
    
    int currentId = 0;
    public void showAllData(int itu){
        
        ArrayList<BalanceData> bd = new ArrayList<BalanceData>();
        bd = conDB.getUserBalance(itu);
        for(int i = 0; i < bd.size(); i++){
            models.insertRow(models.getRowCount(), new Object[]{bd.get(i).getDate(),bd.get(i).getPrevBalance(), bd.get(i).getAfterBalance(), bd.get(i).getTransaction()});
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        balanceDataTbl = new javax.swing.JTable();
        usernameLbl = new javax.swing.JLabel();
        unametittleLbl = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        pullTF = new javax.swing.JTextField();
        addTF = new javax.swing.JTextField();
        pullLbl = new javax.swing.JLabel();
        AddLbl = new javax.swing.JLabel();
        pullBtn = new javax.swing.JButton();
        addBtn = new javax.swing.JButton();
        balSumLbl = new javax.swing.JLabel();
        balSUMAmountLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        balanceDataTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Saldo Sebelumnya", "Saldo Setelah", "Jenis Transaksi"
            }
        ));
        jScrollPane1.setViewportView(balanceDataTbl);

        usernameLbl.setText("jLabel1");

        unametittleLbl.setText("Username : ");

        backBtn.setText("Kembali");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        pullLbl.setText("Tarik Uang :");

        AddLbl.setText("Tambah Saldo : ");

        pullBtn.setText("Tarik");
        pullBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pullBtnActionPerformed(evt);
            }
        });

        addBtn.setText("Tambah");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        balSumLbl.setText("Total Saldo : ");

        balSUMAmountLbl.setText("Amount");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(balSumLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(backBtn)
                        .addGap(22, 22, 22))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 507, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(unametittleLbl)
                                        .addGap(18, 18, 18)
                                        .addComponent(usernameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(pullLbl)
                                            .addComponent(AddLbl))
                                        .addGap(27, 27, 27)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(balSUMAmountLbl)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(addTF, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(addBtn))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(pullTF, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(pullBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameLbl)
                    .addComponent(unametittleLbl))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pullTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pullLbl)
                    .addComponent(pullBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddLbl)
                    .addComponent(addBtn))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backBtn)
                    .addComponent(balSumLbl)
                    .addComponent(balSUMAmountLbl))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        new Login().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_backBtnActionPerformed

    private void pullBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pullBtnActionPerformed
        // TODO add your handling code here:
        int pullAmount = Integer.parseInt(pullTF.getText());
        if(pullAmount < 0){
            JOptionPane.showMessageDialog(this, "Penarikan tidak boleh negatif");
        } else if(pullAmount < 1){
            JOptionPane.showMessageDialog(this, "Penarikan tidak boleh nol");
        } else{
            pullAmount *= -1;
            if(checkValidPull(currentId,pullAmount)){
                conDB.userPullBalance(currentId, pullAmount);
                reloadData();
                pullTF.setText("");
            } else{
                JOptionPane.showMessageDialog(this, "Tidak dapat melakukan penarikan lebih dari saldo : " + conDB.getLastBalance(currentId));
                pullTF.setText("");
            }
        }
        
        balSUMAmountLbl.setText("" + conDB.getLastBalance(currentId));
    }//GEN-LAST:event_pullBtnActionPerformed

    private boolean checkValidPull(int curID, int amon){
        conDB.connect();
        if(conDB.getLastBalance(curID) + amon  >= 0){
            return true;
        } else{
            return false;
        }
    }
    
    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
        int pushAmount = Integer.parseInt(addTF.getText());
        conDB.connect();
        if(pushAmount < 0){
            JOptionPane.showMessageDialog(this, "Penambahan tidak boleh negatif");
        } else if(pushAmount < 1){
            JOptionPane.showMessageDialog(this, "Penambahan tidak boleh nol");
        } else{
            conDB.userPushBalance(currentId, pushAmount);
        }
        
        reloadData();
        addTF.setText("");
        balSUMAmountLbl.setText("" + conDB.getLastBalance(currentId));
    }//GEN-LAST:event_addBtnActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddLbl;
    private javax.swing.JButton addBtn;
    private javax.swing.JTextField addTF;
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel balSUMAmountLbl;
    private javax.swing.JLabel balSumLbl;
    private javax.swing.JTable balanceDataTbl;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton pullBtn;
    private javax.swing.JLabel pullLbl;
    private javax.swing.JTextField pullTF;
    private javax.swing.JLabel unametittleLbl;
    private javax.swing.JLabel usernameLbl;
    // End of variables declaration//GEN-END:variables
}
