/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MyBankApp;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Anton Roycar Nababan
 */

public class Login extends javax.swing.JFrame {
    ConnectDB conDB = new ConnectDB();
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usernameTF = new javax.swing.JTextField();
        usernameLbl = new javax.swing.JLabel();
        pinLbl = new javax.swing.JLabel();
        pinTF = new javax.swing.JTextField();
        loginBtn = new javax.swing.JButton();
        tittleLbl = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        usernameLbl.setText("Username");

        pinLbl.setText("PIN");

        loginBtn.setText("Login");
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });

        tittleLbl.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        tittleLbl.setText("Login Page");

        jLabel1.setText("Admin");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tittleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(usernameLbl)
                                    .addComponent(pinLbl))
                                .addGap(48, 48, 48)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(usernameTF)
                                    .addComponent(pinTF, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                    .addComponent(loginBtn, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(tittleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usernameLbl))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pinLbl)
                    .addComponent(pinTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(loginBtn)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        // TODO add your handling code here:
                // TODO add your handling code here:
        conDB.connect();
        String checkUsername = usernameTF.getText();
        int k = conDB.checkUsername(checkUsername);
        if(k > 0){
            if(conDB.getBlockInfo(k)){
                 JOptionPane.showMessageDialog(this, "Username telah Diblokir. Silahkan hubungi admin untuk info lebih lanjut");
            }else{
                if(login()){
                new BalancePage(b, it).setVisible(true);
                setVisible(false);
                }
            }
        }
        
    }//GEN-LAST:event_loginBtnActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        new AdminMenu().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jLabel1MouseClicked

    String b = "";
    int it = 0;
    
    private boolean login(){
        conDB.connect();
        String checkUsername = usernameTF.getText();
        String checkPIN = pinTF.getText();
        int k = conDB.checkUsername(checkUsername);
        
        ArrayList<User> ua = new ArrayList<User>();
        ua = conDB.getAllUser();
        boolean checklogin = true;
        for(int i = 0; i < ua.size(); i++){
            if((checkUsername.equals(ua.get(i).getName())) && (checkPIN.equals(ua.get(i).getPin()))){
                JOptionPane.showMessageDialog(this, "login berhasil");
                it = ua.get(i).getId();
                b = checkUsername;
                checklogin = false;
                return true;
            }
        }
        if(checklogin){
            JOptionPane.showMessageDialog(this, "username/password salah");
            if(k > 0){
                conDB.blockUser(k);
                if(conDB.getBlockInfo(k)){
                 JOptionPane.showMessageDialog(this, "Username telah Diblokir. Silahkan hubungi admin untuk info lebih lanjut");
            }
            }
            return false;
        }
        return false;
    }
    
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton loginBtn;
    private javax.swing.JLabel pinLbl;
    private javax.swing.JTextField pinTF;
    private javax.swing.JLabel tittleLbl;
    private javax.swing.JLabel usernameLbl;
    private javax.swing.JTextField usernameTF;
    // End of variables declaration//GEN-END:variables
}
